### ISSUE TITLE
Availability?

### ISSUE THREAD

**Issue by ShiftySituation** [shlomiassaf/table-demo#1]
When will Angrid be available?  This is the most comprehensive table that solves all of our demands but I don't see a package anywhere.

**Comment by shlomiassaf** [comment]
I'm working on this, but on my free time so its in progress...

I hope within the next month but no promises.... :)

**Comment by AbhijithSugunan** [comment]
Is it ready to ship ?

**Comment by ghost** [comment]
Any update can we help?

**Comment by shlomiassaf** [comment]
Yes, now available.

https://github.com/shlomiassaf/ngrid
